module Crul
  @[Link("curl")]
  lib C
    SOCKET_BAD = -1
    MAX_WRITE_SIZE = 16384
    WRITEFUNC_PAUSE = 268435457
    CHUNK_BGN_FUNC_OK = 0
    CHUNK_BGN_FUNC_FAIL = 1
    CHUNK_BGN_FUNC_SKIP = 2
    CHUNK_END_FUNC_OK = 0
    CHUNK_END_FUNC_FAIL = 1
    FNMATCHFUNC_MATCH = 0
    FNMATCHFUNC_NOMATCH = 1
    FNMATCHFUNC_FAIL = 2
    SEEKFUNC_OK = 0
    SEEKFUNC_FAIL = 1
    SEEKFUNC_CANTSEEK = 2
    READFUNC_ABORT = 268435456
    READFUNC_PAUSE = 268435457
    SOCKOPT_OK = 0
    SOCKOPT_ERROR = 1
    SOCKOPT_ALREADY_CONNECTED = 2
    E_ALREADY_COMPLETE = 99999
    SSH_AUTH_NONE = 0
    GSSAPI_DELEGATION_NONE = 0
    ERROR_SIZE = 256
    HEADER_UNIFIED = 0
    OPTTYPE_LONG = 0
    OPTTYPE_OBJECTPOINT = 10000
    OPTTYPE_STRINGPOINT = 10000
    OPTTYPE_FUNCTIONPOINT = 20000
    OPTTYPE_OFF_T = 30000
    IPRESOLVE_WHATEVER = 0
    IPRESOLVE_V4 = 1
    IPRESOLVE_V6 = 2
    REDIR_GET_ALL = 0
    REDIR_POST_301 = 1
    REDIR_POST_302 = 2
    REDIR_POST_303 = 4
    SSLBACKEND_LIBRESSL = 1
    SSLBACKEND_BORINGSSL = 1
    SSLBACKEND_WOLFSSL = 6
    INFO_STRING = 1048576
    INFO_LONG = 2097152
    INFO_DOUBLE = 3145728
    INFO_SLIST = 4194304
    INFO_SOCKET = 5242880
    INFO_MASK = 1048575
    INFO_TYPEMASK = 15728640
    GLOBAL_NOTHING = 0
    WAIT_POLLIN = 1
    WAIT_POLLPRI = 2
    WAIT_POLLOUT = 4
    POLL_NONE = 0
    POLL_IN = 1
    POLL_OUT = 2
    POLL_INOUT = 3
    POLL_REMOVE = 4
    CSELECT_IN = 1
    CSELECT_OUT = 2
    CSELECT_ERR = 4
    PUSH_OK = 0
    PUSH_DENY = 1
    struct Httppost
      next : Httppost*
      name : LibC::Char*
      namelength : LibC::Long
      contents : LibC::Char*
      contentslength : LibC::Long
      buffer : LibC::Char*
      bufferlength : LibC::Long
      contenttype : LibC::Char*
      contentheader : Slist*
      more : Httppost*
      flags : LibC::Long
      showfilename : LibC::Char*
      userp : Void*
      contentlen : LibC::Int
    end
    struct Slist
      data : LibC::Char*
      next : Slist*
    end
    FiletypeFile = 0
    FiletypeDirectory = 1
    FiletypeSymlink = 2
    FiletypeDeviceBlock = 3
    FiletypeDeviceChar = 4
    FiletypeNamedpipe = 5
    FiletypeSocket = 6
    FiletypeDoor = 7
    FiletypeUnknown = 8
    struct Fileinfo
      filename : LibC::Char*
      filetype : Filetype
      time : TimeT
      perm : LibC::UInt
      uid : LibC::Int
      gid : LibC::Int
      size : LibC::Int
      hardlinks : LibC::Long
      strings : FileinfoStrings
      flags : LibC::UInt
      b_data : LibC::Char*
      b_size : LibC::SizeT
      b_used : LibC::SizeT
    end
    enum Filetype
      FiletypeFile = 0
      FiletypeDirectory = 1
      FiletypeSymlink = 2
      FiletypeDeviceBlock = 3
      FiletypeDeviceChar = 4
      FiletypeNamedpipe = 5
      FiletypeSocket = 6
      FiletypeDoor = 7
      FiletypeUnknown = 8
    end
    alias X__DarwinTimeT = LibC::Long
    alias TimeT = X__DarwinTimeT
    struct FileinfoStrings
      time : LibC::Char*
      perm : LibC::Char*
      user : LibC::Char*
      group : LibC::Char*
      target : LibC::Char*
    end
    SocktypeIpcxn = 0
    SocktypeAccept = 1
    SocktypeLast = 2
    struct CurlSockaddr
      family : LibC::Int
      socktype : LibC::Int
      protocol : LibC::Int
      addrlen : LibC::UInt
      addr : Sockaddr
    end
    struct Sockaddr
      sa_len : X__Uint8T
      sa_family : SaFamilyT
      sa_data : LibC::Char[14]
    end
    alias X__Uint8T = UInt8
    alias SaFamilyT = X__Uint8T
    IoeOk = 0
    IoeUnknowncmd = 1
    IoeFailrestart = 2
    IoeLast = 3
    IocmdNop = 0
    IocmdRestartread = 1
    IocmdLast = 2
    InfoText = 0
    InfoHeaderIn = 1
    InfoHeaderOut = 2
    InfoDataIn = 3
    InfoDataOut = 4
    InfoSslDataIn = 5
    InfoSslDataOut = 6
    InfoEnd = 7
    EOk = 0
    EUnsupportedProtocol = 1
    EFailedInit = 2
    EUrlMalformat = 3
    ENotBuiltIn = 4
    ECouldntResolveProxy = 5
    ECouldntResolveHost = 6
    ECouldntConnect = 7
    EWeirdServerReply = 8
    ERemoteAccessDenied = 9
    EFtpAcceptFailed = 10
    EFtpWeirdPassReply = 11
    EFtpAcceptTimeout = 12
    EFtpWeirdPasvReply = 13
    EFtpWeird227Format = 14
    EFtpCantGetHost = 15
    EHttp2 = 16
    EFtpCouldntSetType = 17
    EPartialFile = 18
    EFtpCouldntRetrFile = 19
    EObsolete20 = 20
    EQuoteError = 21
    EHttpReturnedError = 22
    EWriteError = 23
    EObsolete24 = 24
    EUploadFailed = 25
    EReadError = 26
    EOutOfMemory = 27
    EOperationTimedout = 28
    EObsolete29 = 29
    EFtpPortFailed = 30
    EFtpCouldntUseRest = 31
    EObsolete32 = 32
    ERangeError = 33
    EHttpPostError = 34
    ESslConnectError = 35
    EBadDownloadResume = 36
    EFileCouldntReadFile = 37
    ELdapCannotBind = 38
    ELdapSearchFailed = 39
    EObsolete40 = 40
    EFunctionNotFound = 41
    EAbortedByCallback = 42
    EBadFunctionArgument = 43
    EObsolete44 = 44
    EInterfaceFailed = 45
    EObsolete46 = 46
    ETooManyRedirects = 47
    EUnknownOption = 48
    ETelnetOptionSyntax = 49
    EObsolete50 = 50
    EPeerFailedVerification = 51
    EGotNothing = 52
    ESslEngineNotfound = 53
    ESslEngineSetfailed = 54
    ESendError = 55
    ERecvError = 56
    EObsolete57 = 57
    ESslCertproblem = 58
    ESslCipher = 59
    ESslCacert = 60
    EBadContentEncoding = 61
    ELdapInvalidUrl = 62
    EFilesizeExceeded = 63
    EUseSslFailed = 64
    ESendFailRewind = 65
    ESslEngineInitfailed = 66
    ELoginDenied = 67
    ETftpNotfound = 68
    ETftpPerm = 69
    ERemoteDiskFull = 70
    ETftpIllegal = 71
    ETftpUnknownid = 72
    ERemoteFileExists = 73
    ETftpNosuchuser = 74
    EConvFailed = 75
    EConvReqd = 76
    ESslCacertBadfile = 77
    ERemoteFileNotFound = 78
    ESsh = 79
    ESslShutdownFailed = 80
    EAgain = 81
    ESslCrlBadfile = 82
    ESslIssuerError = 83
    EFtpPretFailed = 84
    ERtspCseqError = 85
    ERtspSessionError = 86
    EFtpBadFileList = 87
    EChunkFailed = 88
    ENoConnectionAvailable = 89
    ESslPinnedpubkeynotmatch = 90
    ESslInvalidcertstatus = 91
    EHttp2Stream = 92
    Last = 93
    ProxyHttp = 0
    ProxyHttp10 = 1
    ProxyHttps = 2
    ProxySocks4 = 4
    ProxySocks5 = 5
    ProxySocks4a = 6
    ProxySocks5Hostname = 7
    struct Khkey
      key : LibC::Char*
      len : LibC::SizeT
      keytype : Khtype
    end
    enum Khtype
      KhtypeUnknown = 0
      KhtypeRsa1 = 1
      KhtypeRsa = 2
      KhtypeDss = 3
    end
    UsesslNone = 0
    UsesslTry = 1
    UsesslControl = 2
    UsesslAll = 3
    UsesslLast = 4
    FtpsslCccNone = 0
    FtpsslCccPassive = 1
    FtpsslCccActive = 2
    FtpsslCccLast = 3
    FtpauthDefault = 0
    FtpauthSsl = 1
    FtpauthTls = 2
    FtpauthLast = 3
    FtpCreateDirNone = 0
    FtpCreateDir = 1
    FtpCreateDirRetry = 2
    FtpCreateDirLast = 3
    FtpmethodDefault = 0
    FtpmethodMulticwd = 1
    FtpmethodNocwd = 2
    FtpmethodSinglecwd = 3
    FtpmethodLast = 4
    OptWritedata = 10001
    OptUrl = 10002
    OptPort = 3
    OptProxy = 10004
    OptUserpwd = 10005
    OptProxyuserpwd = 10006
    OptRange = 10007
    OptReaddata = 10009
    OptErrorbuffer = 10010
    OptWritefunction = 20011
    OptReadfunction = 20012
    OptTimeout = 13
    OptInfilesize = 14
    OptPostfields = 10015
    OptReferer = 10016
    OptFtpport = 10017
    OptUseragent = 10018
    OptLowSpeedLimit = 19
    OptLowSpeedTime = 20
    OptResumeFrom = 21
    OptCookie = 10022
    OptHttpheader = 10023
    OptHttppost = 10024
    OptSslcert = 10025
    OptKeypasswd = 10026
    OptCrlf = 27
    OptQuote = 10028
    OptHeaderdata = 10029
    OptCookiefile = 10031
    OptSslversion = 32
    OptTimecondition = 33
    OptTimevalue = 34
    OptCustomrequest = 10036
    OptStderr = 10037
    OptPostquote = 10039
    OptObsolete40 = 10040
    OptVerbose = 41
    OptHeader = 42
    OptNoprogress = 43
    OptNobody = 44
    OptFailonerror = 45
    OptUpload = 46
    OptPost = 47
    OptDirlistonly = 48
    OptAppend = 50
    OptNetrc = 51
    OptFollowlocation = 52
    OptTransfertext = 53
    OptPut = 54
    OptProgressfunction = 20056
    OptProgressdata = 10057
    OptAutoreferer = 58
    OptProxyport = 59
    OptPostfieldsize = 60
    OptHttpproxytunnel = 61
    OptInterface = 10062
    OptKrblevel = 10063
    OptSslVerifypeer = 64
    OptCainfo = 10065
    OptMaxredirs = 68
    OptFiletime = 69
    OptTelnetoptions = 10070
    OptMaxconnects = 71
    OptObsolete72 = 72
    OptFreshConnect = 74
    OptForbidReuse = 75
    OptRandomFile = 10076
    OptEgdsocket = 10077
    OptConnecttimeout = 78
    OptHeaderfunction = 20079
    OptHttpget = 80
    OptSslVerifyhost = 81
    OptCookiejar = 10082
    OptSslCipherList = 10083
    OptHttpVersion = 84
    OptFtpUseEpsv = 85
    OptSslcerttype = 10086
    OptSslkey = 10087
    OptSslkeytype = 10088
    OptSslengine = 10089
    OptSslengineDefault = 90
    OptDnsUseGlobalCache = 91
    OptDnsCacheTimeout = 92
    OptPrequote = 10093
    OptDebugfunction = 20094
    OptDebugdata = 10095
    OptCookiesession = 96
    OptCapath = 10097
    OptBuffersize = 98
    OptNosignal = 99
    OptShare = 10100
    OptProxytype = 101
    OptAcceptEncoding = 10102
    OptPrivate = 10103
    OptHttp200aliases = 10104
    OptUnrestrictedAuth = 105
    OptFtpUseEprt = 106
    OptHttpauth = 107
    OptSslCtxFunction = 20108
    OptSslCtxData = 10109
    OptFtpCreateMissingDirs = 110
    OptProxyauth = 111
    OptFtpResponseTimeout = 112
    OptIpresolve = 113
    OptMaxfilesize = 114
    OptInfilesizeLarge = 30115
    OptResumeFromLarge = 30116
    OptMaxfilesizeLarge = 30117
    OptNetrcFile = 10118
    OptUseSsl = 119
    OptPostfieldsizeLarge = 30120
    OptTcpNodelay = 121
    OptFtpsslauth = 129
    OptIoctlfunction = 20130
    OptIoctldata = 10131
    OptFtpAccount = 10134
    OptCookielist = 10135
    OptIgnoreContentLength = 136
    OptFtpSkipPasvIp = 137
    OptFtpFilemethod = 138
    OptLocalport = 139
    OptLocalportrange = 140
    OptConnectOnly = 141
    OptConvFromNetworkFunction = 20142
    OptConvToNetworkFunction = 20143
    OptConvFromUtf8Function = 20144
    OptMaxSendSpeedLarge = 30145
    OptMaxRecvSpeedLarge = 30146
    OptFtpAlternativeToUser = 10147
    OptSockoptfunction = 20148
    OptSockoptdata = 10149
    OptSslSessionidCache = 150
    OptSshAuthTypes = 151
    OptSshPublicKeyfile = 10152
    OptSshPrivateKeyfile = 10153
    OptFtpSslCcc = 154
    OptTimeoutMs = 155
    OptConnecttimeoutMs = 156
    OptHttpTransferDecoding = 157
    OptHttpContentDecoding = 158
    OptNewFilePerms = 159
    OptNewDirectoryPerms = 160
    OptPostredir = 161
    OptSshHostPublicKeyMd5 = 10162
    OptOpensocketfunction = 20163
    OptOpensocketdata = 10164
    OptCopypostfields = 10165
    OptProxyTransferMode = 166
    OptSeekfunction = 20167
    OptSeekdata = 10168
    OptCrlfile = 10169
    OptIssuercert = 10170
    OptAddressScope = 171
    OptCertinfo = 172
    OptUsername = 10173
    OptPassword = 10174
    OptProxyusername = 10175
    OptProxypassword = 10176
    OptNoproxy = 10177
    OptTftpBlksize = 178
    OptSocks5GssapiService = 10179
    OptSocks5GssapiNec = 180
    OptProtocols = 181
    OptRedirProtocols = 182
    OptSshKnownhosts = 10183
    OptSshKeyfunction = 20184
    OptSshKeydata = 10185
    OptMailFrom = 10186
    OptMailRcpt = 10187
    OptFtpUsePret = 188
    OptRtspRequest = 189
    OptRtspSessionId = 10190
    OptRtspStreamUri = 10191
    OptRtspTransport = 10192
    OptRtspClientCseq = 193
    OptRtspServerCseq = 194
    OptInterleavedata = 10195
    OptInterleavefunction = 20196
    OptWildcardmatch = 197
    OptChunkBgnFunction = 20198
    OptChunkEndFunction = 20199
    OptFnmatchFunction = 20200
    OptChunkData = 10201
    OptFnmatchData = 10202
    OptResolve = 10203
    OptTlsauthUsername = 10204
    OptTlsauthPassword = 10205
    OptTlsauthType = 10206
    OptTransferEncoding = 207
    OptClosesocketfunction = 20208
    OptClosesocketdata = 10209
    OptGssapiDelegation = 210
    OptDnsServers = 10211
    OptAccepttimeoutMs = 212
    OptTcpKeepalive = 213
    OptTcpKeepidle = 214
    OptTcpKeepintvl = 215
    OptSslOptions = 216
    OptMailAuth = 10217
    OptSaslIr = 218
    OptXferinfofunction = 20219
    OptXoauth2Bearer = 10220
    OptDnsInterface = 10221
    OptDnsLocalIp4 = 10222
    OptDnsLocalIp6 = 10223
    OptLoginOptions = 10224
    OptSslEnableNpn = 225
    OptSslEnableAlpn = 226
    OptExpect100TimeoutMs = 227
    OptProxyheader = 10228
    OptHeaderopt = 229
    OptPinnedpublickey = 10230
    OptUnixSocketPath = 10231
    OptSslVerifystatus = 232
    OptSslFalsestart = 233
    OptPathAsIs = 234
    OptProxyServiceName = 10235
    OptServiceName = 10236
    OptPipewait = 237
    OptDefaultProtocol = 10238
    OptStreamWeight = 239
    OptStreamDepends = 10240
    OptStreamDependsE = 10241
    OptTftpNoOptions = 242
    OptConnectTo = 10243
    OptTcpFastopen = 244
    OptKeepSendingOnError = 245
    OptProxyCainfo = 10246
    OptProxyCapath = 10247
    OptProxySslVerifypeer = 248
    OptProxySslVerifyhost = 249
    OptProxySslversion = 250
    OptProxyTlsauthUsername = 10251
    OptProxyTlsauthPassword = 10252
    OptProxyTlsauthType = 10253
    OptProxySslcert = 10254
    OptProxySslcerttype = 10255
    OptProxySslkey = 10256
    OptProxySslkeytype = 10257
    OptProxyKeypasswd = 10258
    OptProxySslCipherList = 10259
    OptProxyCrlfile = 10260
    OptProxySslOptions = 261
    OptPreProxy = 10262
    OptProxyPinnedpublickey = 10263
    OptLastentry = 10264
    HttpVersionNone = 0
    HttpVersion10 = 1
    HttpVersion11 = 2
    HttpVersion20 = 3
    HttpVersion2tls = 4
    HttpVersion2PriorKnowledge = 5
    HttpVersionLast = 6
    RtspreqNone = 0
    RtspreqOptions = 1
    RtspreqDescribe = 2
    RtspreqAnnounce = 3
    RtspreqSetup = 4
    RtspreqPlay = 5
    RtspreqPause = 6
    RtspreqTeardown = 7
    RtspreqGetParameter = 8
    RtspreqSetParameter = 9
    RtspreqRecord = 10
    RtspreqReceive = 11
    RtspreqLast = 12
    SslversionDefault = 0
    SslversionTlsv1 = 1
    SslversionSslv2 = 2
    SslversionSslv3 = 3
    SslversionTlsv10 = 4
    SslversionTlsv11 = 5
    SslversionTlsv12 = 6
    SslversionTlsv13 = 7
    SslversionLast = 8
    TimecondNone = 0
    TimecondIfmodsince = 1
    TimecondIfunmodsince = 2
    TimecondLastmod = 3
    TimecondLast = 4
    fun strequal = curl_strequal(s1 : LibC::Char*, s2 : LibC::Char*) : LibC::Int
    fun strnequal = curl_strnequal(s1 : LibC::Char*, s2 : LibC::Char*, n : LibC::SizeT) : LibC::Int
    FormNothing = 0
    FormCopyname = 1
    FormPtrname = 2
    FormNamelength = 3
    FormCopycontents = 4
    FormPtrcontents = 5
    FormContentslength = 6
    FormFilecontent = 7
    FormArray = 8
    FormObsolete = 9
    FormFile = 10
    FormBuffer = 11
    FormBufferptr = 12
    FormBufferlength = 13
    FormContenttype = 14
    FormContentheader = 15
    FormFilename = 16
    FormEnd = 17
    FormObsolete2 = 18
    FormStream = 19
    FormContentlen = 20
    FormLastentry = 21
    struct Forms
      option : Formoption
      value : LibC::Char*
    end
    enum Formoption
      FormNothing = 0
      FormCopyname = 1
      FormPtrname = 2
      FormNamelength = 3
      FormCopycontents = 4
      FormPtrcontents = 5
      FormContentslength = 6
      FormFilecontent = 7
      FormArray = 8
      FormObsolete = 9
      FormFile = 10
      FormBuffer = 11
      FormBufferptr = 12
      FormBufferlength = 13
      FormContenttype = 14
      FormContentheader = 15
      FormFilename = 16
      FormEnd = 17
      FormObsolete2 = 18
      FormStream = 19
      FormContentlen = 20
      FormLastentry = 21
    end
    FormaddOk = 0
    FormaddMemory = 1
    FormaddOptionTwice = 2
    FormaddNull = 3
    FormaddUnknownOption = 4
    FormaddIncomplete = 5
    FormaddIllegalArray = 6
    FormaddDisabled = 7
    FormaddLast = 8
    fun formadd = curl_formadd(httppost : Httppost**, last_post : Httppost**, ...) : Formcode
    enum Formcode
      FormaddOk = 0
      FormaddMemory = 1
      FormaddOptionTwice = 2
      FormaddNull = 3
      FormaddUnknownOption = 4
      FormaddIncomplete = 5
      FormaddIllegalArray = 6
      FormaddDisabled = 7
      FormaddLast = 8
    end
    fun formget = curl_formget(form : Httppost*, arg : Void*, append : FormgetCallback) : LibC::Int
    alias FormgetCallback = (Void*, LibC::Char*, LibC::SizeT -> LibC::SizeT)
    fun formfree = curl_formfree(form : Httppost*)
    fun getenv = curl_getenv(variable : LibC::Char*) : LibC::Char*
    fun version = curl_version : LibC::Char*
    fun easy_escape = curl_easy_escape(handle : Curl*, string : LibC::Char*, length : LibC::Int) : LibC::Char*
    alias Curl = Void
    fun escape = curl_escape(string : LibC::Char*, length : LibC::Int) : LibC::Char*
    fun easy_unescape = curl_easy_unescape(handle : Curl*, string : LibC::Char*, length : LibC::Int, outlength : LibC::Int*) : LibC::Char*
    fun unescape = curl_unescape(string : LibC::Char*, length : LibC::Int) : LibC::Char*
    fun free = curl_free(p : Void*)
    fun global_init = curl_global_init(flags : LibC::Long) : Code
    enum Code
      EOk = 0
      EUnsupportedProtocol = 1
      EFailedInit = 2
      EUrlMalformat = 3
      ENotBuiltIn = 4
      ECouldntResolveProxy = 5
      ECouldntResolveHost = 6
      ECouldntConnect = 7
      EWeirdServerReply = 8
      ERemoteAccessDenied = 9
      EFtpAcceptFailed = 10
      EFtpWeirdPassReply = 11
      EFtpAcceptTimeout = 12
      EFtpWeirdPasvReply = 13
      EFtpWeird227Format = 14
      EFtpCantGetHost = 15
      EHttp2 = 16
      EFtpCouldntSetType = 17
      EPartialFile = 18
      EFtpCouldntRetrFile = 19
      EObsolete20 = 20
      EQuoteError = 21
      EHttpReturnedError = 22
      EWriteError = 23
      EObsolete24 = 24
      EUploadFailed = 25
      EReadError = 26
      EOutOfMemory = 27
      EOperationTimedout = 28
      EObsolete29 = 29
      EFtpPortFailed = 30
      EFtpCouldntUseRest = 31
      EObsolete32 = 32
      ERangeError = 33
      EHttpPostError = 34
      ESslConnectError = 35
      EBadDownloadResume = 36
      EFileCouldntReadFile = 37
      ELdapCannotBind = 38
      ELdapSearchFailed = 39
      EObsolete40 = 40
      EFunctionNotFound = 41
      EAbortedByCallback = 42
      EBadFunctionArgument = 43
      EObsolete44 = 44
      EInterfaceFailed = 45
      EObsolete46 = 46
      ETooManyRedirects = 47
      EUnknownOption = 48
      ETelnetOptionSyntax = 49
      EObsolete50 = 50
      EPeerFailedVerification = 51
      EGotNothing = 52
      ESslEngineNotfound = 53
      ESslEngineSetfailed = 54
      ESendError = 55
      ERecvError = 56
      EObsolete57 = 57
      ESslCertproblem = 58
      ESslCipher = 59
      ESslCacert = 60
      EBadContentEncoding = 61
      ELdapInvalidUrl = 62
      EFilesizeExceeded = 63
      EUseSslFailed = 64
      ESendFailRewind = 65
      ESslEngineInitfailed = 66
      ELoginDenied = 67
      ETftpNotfound = 68
      ETftpPerm = 69
      ERemoteDiskFull = 70
      ETftpIllegal = 71
      ETftpUnknownid = 72
      ERemoteFileExists = 73
      ETftpNosuchuser = 74
      EConvFailed = 75
      EConvReqd = 76
      ESslCacertBadfile = 77
      ERemoteFileNotFound = 78
      ESsh = 79
      ESslShutdownFailed = 80
      EAgain = 81
      ESslCrlBadfile = 82
      ESslIssuerError = 83
      EFtpPretFailed = 84
      ERtspCseqError = 85
      ERtspSessionError = 86
      EFtpBadFileList = 87
      EChunkFailed = 88
      ENoConnectionAvailable = 89
      ESslPinnedpubkeynotmatch = 90
      ESslInvalidcertstatus = 91
      EHttp2Stream = 92
      Last = 93
    end
    fun global_init_mem = curl_global_init_mem(flags : LibC::Long, m : MallocCallback, f : FreeCallback, r : ReallocCallback, s : StrdupCallback, c : CallocCallback) : Code
    alias MallocCallback = (LibC::SizeT -> Void*)
    alias FreeCallback = (Void* -> Void)
    alias ReallocCallback = (Void*, LibC::SizeT -> Void*)
    alias StrdupCallback = (LibC::Char* -> LibC::Char*)
    alias CallocCallback = (LibC::SizeT, LibC::SizeT -> Void*)
    fun global_cleanup = curl_global_cleanup
    fun slist_append = curl_slist_append(x0 : Slist*, x1 : LibC::Char*) : Slist*
    fun slist_free_all = curl_slist_free_all(x0 : Slist*)
    fun getdate = curl_getdate(p : LibC::Char*, unused : TimeT*) : TimeT
    struct Certinfo
      num_of_certs : LibC::Int
      certinfo : Slist**
    end
    SslbackendNone = 0
    SslbackendOpenssl = 1
    SslbackendGnutls = 2
    SslbackendNss = 3
    SslbackendObsolete4 = 4
    SslbackendGskit = 5
    SslbackendPolarssl = 6
    SslbackendCyassl = 7
    SslbackendSchannel = 8
    SslbackendDarwinssl = 9
    SslbackendAxtls = 10
    SslbackendMbedtls = 11
    struct Tlssessioninfo
      backend : Sslbackend
      internals : Void*
    end
    enum Sslbackend
      SslbackendNone = 0
      SslbackendOpenssl = 1
      SslbackendGnutls = 2
      SslbackendNss = 3
      SslbackendObsolete4 = 4
      SslbackendGskit = 5
      SslbackendPolarssl = 6
      SslbackendCyassl = 7
      SslbackendSchannel = 8
      SslbackendDarwinssl = 9
      SslbackendAxtls = 10
      SslbackendMbedtls = 11
    end
    InfoNone = 0
    InfoEffectiveUrl = 1048577
    InfoResponseCode = 2097154
    InfoTotalTime = 3145731
    InfoNamelookupTime = 3145732
    InfoConnectTime = 3145733
    InfoPretransferTime = 3145734
    InfoSizeUpload = 3145735
    InfoSizeDownload = 3145736
    InfoSpeedDownload = 3145737
    InfoSpeedUpload = 3145738
    InfoHeaderSize = 2097163
    InfoRequestSize = 2097164
    InfoSslVerifyresult = 2097165
    InfoFiletime = 2097166
    InfoContentLengthDownload = 3145743
    InfoContentLengthUpload = 3145744
    InfoStarttransferTime = 3145745
    InfoContentType = 1048594
    InfoRedirectTime = 3145747
    InfoRedirectCount = 2097172
    InfoPrivate = 1048597
    InfoHttpConnectcode = 2097174
    InfoHttpauthAvail = 2097175
    InfoProxyauthAvail = 2097176
    InfoOsErrno = 2097177
    InfoNumConnects = 2097178
    InfoSslEngines = 4194331
    InfoCookielist = 4194332
    InfoLastsocket = 2097181
    InfoFtpEntryPath = 1048606
    InfoRedirectUrl = 1048607
    InfoPrimaryIp = 1048608
    InfoAppconnectTime = 3145761
    InfoCertinfo = 4194338
    InfoConditionUnmet = 2097187
    InfoRtspSessionId = 1048612
    InfoRtspClientCseq = 2097189
    InfoRtspServerCseq = 2097190
    InfoRtspCseqRecv = 2097191
    InfoPrimaryPort = 2097192
    InfoLocalIp = 1048617
    InfoLocalPort = 2097194
    InfoTlsSession = 4194347
    InfoActivesocket = 5242924
    InfoTlsSslPtr = 4194349
    InfoHttpVersion = 2097198
    InfoProxySslVerifyresult = 2097199
    InfoProtocol = 2097200
    InfoScheme = 1048625
    InfoLastone = 49
    ClosepolicyNone = 0
    ClosepolicyOldest = 1
    ClosepolicyLeastRecentlyUsed = 2
    ClosepolicyLeastTraffic = 3
    ClosepolicySlowest = 4
    ClosepolicyCallback = 5
    ClosepolicyLast = 6
    LockDataNone = 0
    LockDataShare = 1
    LockDataCookie = 2
    LockDataDns = 3
    LockDataSslSession = 4
    LockDataConnect = 5
    LockDataLast = 6
    LockAccessNone = 0
    LockAccessShared = 1
    LockAccessSingle = 2
    LockAccessLast = 3
    SheOk = 0
    SheBadOption = 1
    SheInUse = 2
    SheInvalid = 3
    SheNomem = 4
    SheNotBuiltIn = 5
    SheLast = 6
    ShoptNone = 0
    ShoptShare = 1
    ShoptUnshare = 2
    ShoptLockfunc = 3
    ShoptUnlockfunc = 4
    ShoptUserdata = 5
    ShoptLast = 6
    fun share_init = curl_share_init : Sh*
    alias Sh = Void
    fun share_setopt = curl_share_setopt(x0 : Sh*, option : Shoption, ...) : Shcode
    enum Shoption
      ShoptNone = 0
      ShoptShare = 1
      ShoptUnshare = 2
      ShoptLockfunc = 3
      ShoptUnlockfunc = 4
      ShoptUserdata = 5
      ShoptLast = 6
    end
    enum Shcode
      SheOk = 0
      SheBadOption = 1
      SheInUse = 2
      SheInvalid = 3
      SheNomem = 4
      SheNotBuiltIn = 5
      SheLast = 6
    end
    fun share_cleanup = curl_share_cleanup(x0 : Sh*) : Shcode
    VersionFirst = 0
    VersionSecond = 1
    VersionThird = 2
    VersionFourth = 3
    VersionLast = 4
    fun version_info = curl_version_info(x0 : Version) : VersionInfoData*
    enum Version
      VersionFirst = 0
      VersionSecond = 1
      VersionThird = 2
      VersionFourth = 3
      VersionLast = 4
    end
    struct VersionInfoData
      age : Version
      version : LibC::Char*
      version_num : LibC::UInt
      host : LibC::Char*
      features : LibC::Int
      ssl_version : LibC::Char*
      ssl_version_num : LibC::Long
      libz_version : LibC::Char*
      protocols : LibC::Char**
      ares : LibC::Char*
      ares_num : LibC::Int
      libidn : LibC::Char*
      iconv_ver_num : LibC::Int
      libssh_version : LibC::Char*
    end
    fun easy_strerror = curl_easy_strerror(x0 : Code) : LibC::Char*
    fun share_strerror = curl_share_strerror(x0 : Shcode) : LibC::Char*
    fun easy_pause = curl_easy_pause(handle : Curl*, bitmask : LibC::Int) : Code
    fun easy_init = curl_easy_init : Curl*
    fun easy_setopt = curl_easy_setopt(curl : Curl*, option : Option, ...) : Code
    enum Option
      OptWritedata = 10001
      OptUrl = 10002
      OptPort = 3
      OptProxy = 10004
      OptUserpwd = 10005
      OptProxyuserpwd = 10006
      OptRange = 10007
      OptReaddata = 10009
      OptErrorbuffer = 10010
      OptWritefunction = 20011
      OptReadfunction = 20012
      OptTimeout = 13
      OptInfilesize = 14
      OptPostfields = 10015
      OptReferer = 10016
      OptFtpport = 10017
      OptUseragent = 10018
      OptLowSpeedLimit = 19
      OptLowSpeedTime = 20
      OptResumeFrom = 21
      OptCookie = 10022
      OptHttpheader = 10023
      OptHttppost = 10024
      OptSslcert = 10025
      OptKeypasswd = 10026
      OptCrlf = 27
      OptQuote = 10028
      OptHeaderdata = 10029
      OptCookiefile = 10031
      OptSslversion = 32
      OptTimecondition = 33
      OptTimevalue = 34
      OptCustomrequest = 10036
      OptStderr = 10037
      OptPostquote = 10039
      OptObsolete40 = 10040
      OptVerbose = 41
      OptHeader = 42
      OptNoprogress = 43
      OptNobody = 44
      OptFailonerror = 45
      OptUpload = 46
      OptPost = 47
      OptDirlistonly = 48
      OptAppend = 50
      OptNetrc = 51
      OptFollowlocation = 52
      OptTransfertext = 53
      OptPut = 54
      OptProgressfunction = 20056
      OptProgressdata = 10057
      OptAutoreferer = 58
      OptProxyport = 59
      OptPostfieldsize = 60
      OptHttpproxytunnel = 61
      OptInterface = 10062
      OptKrblevel = 10063
      OptSslVerifypeer = 64
      OptCainfo = 10065
      OptMaxredirs = 68
      OptFiletime = 69
      OptTelnetoptions = 10070
      OptMaxconnects = 71
      OptObsolete72 = 72
      OptFreshConnect = 74
      OptForbidReuse = 75
      OptRandomFile = 10076
      OptEgdsocket = 10077
      OptConnecttimeout = 78
      OptHeaderfunction = 20079
      OptHttpget = 80
      OptSslVerifyhost = 81
      OptCookiejar = 10082
      OptSslCipherList = 10083
      OptHttpVersion = 84
      OptFtpUseEpsv = 85
      OptSslcerttype = 10086
      OptSslkey = 10087
      OptSslkeytype = 10088
      OptSslengine = 10089
      OptSslengineDefault = 90
      OptDnsUseGlobalCache = 91
      OptDnsCacheTimeout = 92
      OptPrequote = 10093
      OptDebugfunction = 20094
      OptDebugdata = 10095
      OptCookiesession = 96
      OptCapath = 10097
      OptBuffersize = 98
      OptNosignal = 99
      OptShare = 10100
      OptProxytype = 101
      OptAcceptEncoding = 10102
      OptPrivate = 10103
      OptHttp200aliases = 10104
      OptUnrestrictedAuth = 105
      OptFtpUseEprt = 106
      OptHttpauth = 107
      OptSslCtxFunction = 20108
      OptSslCtxData = 10109
      OptFtpCreateMissingDirs = 110
      OptProxyauth = 111
      OptFtpResponseTimeout = 112
      OptIpresolve = 113
      OptMaxfilesize = 114
      OptInfilesizeLarge = 30115
      OptResumeFromLarge = 30116
      OptMaxfilesizeLarge = 30117
      OptNetrcFile = 10118
      OptUseSsl = 119
      OptPostfieldsizeLarge = 30120
      OptTcpNodelay = 121
      OptFtpsslauth = 129
      OptIoctlfunction = 20130
      OptIoctldata = 10131
      OptFtpAccount = 10134
      OptCookielist = 10135
      OptIgnoreContentLength = 136
      OptFtpSkipPasvIp = 137
      OptFtpFilemethod = 138
      OptLocalport = 139
      OptLocalportrange = 140
      OptConnectOnly = 141
      OptConvFromNetworkFunction = 20142
      OptConvToNetworkFunction = 20143
      OptConvFromUtf8Function = 20144
      OptMaxSendSpeedLarge = 30145
      OptMaxRecvSpeedLarge = 30146
      OptFtpAlternativeToUser = 10147
      OptSockoptfunction = 20148
      OptSockoptdata = 10149
      OptSslSessionidCache = 150
      OptSshAuthTypes = 151
      OptSshPublicKeyfile = 10152
      OptSshPrivateKeyfile = 10153
      OptFtpSslCcc = 154
      OptTimeoutMs = 155
      OptConnecttimeoutMs = 156
      OptHttpTransferDecoding = 157
      OptHttpContentDecoding = 158
      OptNewFilePerms = 159
      OptNewDirectoryPerms = 160
      OptPostredir = 161
      OptSshHostPublicKeyMd5 = 10162
      OptOpensocketfunction = 20163
      OptOpensocketdata = 10164
      OptCopypostfields = 10165
      OptProxyTransferMode = 166
      OptSeekfunction = 20167
      OptSeekdata = 10168
      OptCrlfile = 10169
      OptIssuercert = 10170
      OptAddressScope = 171
      OptCertinfo = 172
      OptUsername = 10173
      OptPassword = 10174
      OptProxyusername = 10175
      OptProxypassword = 10176
      OptNoproxy = 10177
      OptTftpBlksize = 178
      OptSocks5GssapiService = 10179
      OptSocks5GssapiNec = 180
      OptProtocols = 181
      OptRedirProtocols = 182
      OptSshKnownhosts = 10183
      OptSshKeyfunction = 20184
      OptSshKeydata = 10185
      OptMailFrom = 10186
      OptMailRcpt = 10187
      OptFtpUsePret = 188
      OptRtspRequest = 189
      OptRtspSessionId = 10190
      OptRtspStreamUri = 10191
      OptRtspTransport = 10192
      OptRtspClientCseq = 193
      OptRtspServerCseq = 194
      OptInterleavedata = 10195
      OptInterleavefunction = 20196
      OptWildcardmatch = 197
      OptChunkBgnFunction = 20198
      OptChunkEndFunction = 20199
      OptFnmatchFunction = 20200
      OptChunkData = 10201
      OptFnmatchData = 10202
      OptResolve = 10203
      OptTlsauthUsername = 10204
      OptTlsauthPassword = 10205
      OptTlsauthType = 10206
      OptTransferEncoding = 207
      OptClosesocketfunction = 20208
      OptClosesocketdata = 10209
      OptGssapiDelegation = 210
      OptDnsServers = 10211
      OptAccepttimeoutMs = 212
      OptTcpKeepalive = 213
      OptTcpKeepidle = 214
      OptTcpKeepintvl = 215
      OptSslOptions = 216
      OptMailAuth = 10217
      OptSaslIr = 218
      OptXferinfofunction = 20219
      OptXoauth2Bearer = 10220
      OptDnsInterface = 10221
      OptDnsLocalIp4 = 10222
      OptDnsLocalIp6 = 10223
      OptLoginOptions = 10224
      OptSslEnableNpn = 225
      OptSslEnableAlpn = 226
      OptExpect100TimeoutMs = 227
      OptProxyheader = 10228
      OptHeaderopt = 229
      OptPinnedpublickey = 10230
      OptUnixSocketPath = 10231
      OptSslVerifystatus = 232
      OptSslFalsestart = 233
      OptPathAsIs = 234
      OptProxyServiceName = 10235
      OptServiceName = 10236
      OptPipewait = 237
      OptDefaultProtocol = 10238
      OptStreamWeight = 239
      OptStreamDepends = 10240
      OptStreamDependsE = 10241
      OptTftpNoOptions = 242
      OptConnectTo = 10243
      OptTcpFastopen = 244
      OptKeepSendingOnError = 245
      OptProxyCainfo = 10246
      OptProxyCapath = 10247
      OptProxySslVerifypeer = 248
      OptProxySslVerifyhost = 249
      OptProxySslversion = 250
      OptProxyTlsauthUsername = 10251
      OptProxyTlsauthPassword = 10252
      OptProxyTlsauthType = 10253
      OptProxySslcert = 10254
      OptProxySslcerttype = 10255
      OptProxySslkey = 10256
      OptProxySslkeytype = 10257
      OptProxyKeypasswd = 10258
      OptProxySslCipherList = 10259
      OptProxyCrlfile = 10260
      OptProxySslOptions = 261
      OptPreProxy = 10262
      OptProxyPinnedpublickey = 10263
      OptLastentry = 10264
    end
    fun easy_perform = curl_easy_perform(curl : Curl*) : Code
    fun easy_cleanup = curl_easy_cleanup(curl : Curl*)
    fun easy_getinfo = curl_easy_getinfo(curl : Curl*, info : Info, ...) : Code
    enum Info
      InfoNone = 0
      InfoEffectiveUrl = 1048577
      InfoResponseCode = 2097154
      InfoTotalTime = 3145731
      InfoNamelookupTime = 3145732
      InfoConnectTime = 3145733
      InfoPretransferTime = 3145734
      InfoSizeUpload = 3145735
      InfoSizeDownload = 3145736
      InfoSpeedDownload = 3145737
      InfoSpeedUpload = 3145738
      InfoHeaderSize = 2097163
      InfoRequestSize = 2097164
      InfoSslVerifyresult = 2097165
      InfoFiletime = 2097166
      InfoContentLengthDownload = 3145743
      InfoContentLengthUpload = 3145744
      InfoStarttransferTime = 3145745
      InfoContentType = 1048594
      InfoRedirectTime = 3145747
      InfoRedirectCount = 2097172
      InfoPrivate = 1048597
      InfoHttpConnectcode = 2097174
      InfoHttpauthAvail = 2097175
      InfoProxyauthAvail = 2097176
      InfoOsErrno = 2097177
      InfoNumConnects = 2097178
      InfoSslEngines = 4194331
      InfoCookielist = 4194332
      InfoLastsocket = 2097181
      InfoFtpEntryPath = 1048606
      InfoRedirectUrl = 1048607
      InfoPrimaryIp = 1048608
      InfoAppconnectTime = 3145761
      InfoCertinfo = 4194338
      InfoConditionUnmet = 2097187
      InfoRtspSessionId = 1048612
      InfoRtspClientCseq = 2097189
      InfoRtspServerCseq = 2097190
      InfoRtspCseqRecv = 2097191
      InfoPrimaryPort = 2097192
      InfoLocalIp = 1048617
      InfoLocalPort = 2097194
      InfoTlsSession = 4194347
      InfoActivesocket = 5242924
      InfoTlsSslPtr = 4194349
      InfoHttpVersion = 2097198
      InfoProxySslVerifyresult = 2097199
      InfoProtocol = 2097200
      InfoScheme = 1048625
      InfoLastone = 49
    end
    fun easy_duphandle = curl_easy_duphandle(curl : Curl*) : Curl*
    fun easy_reset = curl_easy_reset(curl : Curl*)
    fun easy_recv = curl_easy_recv(curl : Curl*, buffer : Void*, buflen : LibC::SizeT, n : LibC::SizeT*) : Code
    fun easy_send = curl_easy_send(curl : Curl*, buffer : Void*, buflen : LibC::SizeT, n : LibC::SizeT*) : Code
    MCallMultiPerform = -1
    MOk = 0
    MBadHandle = 1
    MBadEasyHandle = 2
    MOutOfMemory = 3
    MInternalError = 4
    MBadSocket = 5
    MUnknownOption = 6
    MAddedAlready = 7
    MLast = 8
    MsgNone = 0
    MsgDone = 1
    MsgLast = 2
    struct Msg
      msg : Msg_
      easy_handle : Curl*
      data : MsgData
    end
    enum Msg_
      MsgNone = 0
      MsgDone = 1
      MsgLast = 2
    end
    union MsgData
      whatever : Void*
      result : Code
    end
    struct Waitfd
      fd : SocketT
      events : LibC::Short
      revents : LibC::Short
    end
    alias SocketT = LibC::Int
    fun multi_init = curl_multi_init : M*
    alias M = Void
    fun multi_add_handle = curl_multi_add_handle(multi_handle : M*, handle : Curl*) : Mcode
    enum Mcode
      MCallMultiPerform = -1
      MOk = 0
      MBadHandle = 1
      MBadEasyHandle = 2
      MOutOfMemory = 3
      MInternalError = 4
      MBadSocket = 5
      MUnknownOption = 6
      MAddedAlready = 7
      MLast = 8
    end
    fun multi_remove_handle = curl_multi_remove_handle(multi_handle : M*, handle : Curl*) : Mcode
    fun multi_fdset = curl_multi_fdset(multi_handle : M*, read_fd_set : FdSet*, write_fd_set : FdSet*, exc_fd_set : FdSet*, max_fd : LibC::Int*) : Mcode
    struct FdSet
      fds_bits : X__Int32T[32]
    end
    alias X__Int32T = LibC::Int
    fun multi_wait = curl_multi_wait(multi_handle : M*, extra_fds : Waitfd*, extra_nfds : LibC::UInt, timeout_ms : LibC::Int, ret : LibC::Int*) : Mcode
    fun multi_perform = curl_multi_perform(multi_handle : M*, running_handles : LibC::Int*) : Mcode
    fun multi_cleanup = curl_multi_cleanup(multi_handle : M*) : Mcode
    fun multi_info_read = curl_multi_info_read(multi_handle : M*, msgs_in_queue : LibC::Int*) : Msg*
    fun multi_strerror = curl_multi_strerror(x0 : Mcode) : LibC::Char*
    fun multi_socket = curl_multi_socket(multi_handle : M*, s : SocketT, running_handles : LibC::Int*) : Mcode
    fun multi_socket_action = curl_multi_socket_action(multi_handle : M*, s : SocketT, ev_bitmask : LibC::Int, running_handles : LibC::Int*) : Mcode
    fun multi_socket_all = curl_multi_socket_all(multi_handle : M*, running_handles : LibC::Int*) : Mcode
    fun multi_timeout = curl_multi_timeout(multi_handle : M*, milliseconds : LibC::Long*) : Mcode
    MoptSocketfunction = 20001
    MoptSocketdata = 10002
    MoptPipelining = 3
    MoptTimerfunction = 20004
    MoptTimerdata = 10005
    MoptMaxconnects = 6
    MoptMaxHostConnections = 7
    MoptMaxPipelineLength = 8
    MoptContentLengthPenaltySize = 30009
    MoptChunkLengthPenaltySize = 30010
    MoptPipeliningSiteBl = 10011
    MoptPipeliningServerBl = 10012
    MoptMaxTotalConnections = 13
    MoptPushfunction = 20014
    MoptPushdata = 10015
    MoptLastentry = 10016
    fun multi_setopt = curl_multi_setopt(multi_handle : M*, option : Moption, ...) : Mcode
    enum Moption
      MoptSocketfunction = 20001
      MoptSocketdata = 10002
      MoptPipelining = 3
      MoptTimerfunction = 20004
      MoptTimerdata = 10005
      MoptMaxconnects = 6
      MoptMaxHostConnections = 7
      MoptMaxPipelineLength = 8
      MoptContentLengthPenaltySize = 30009
      MoptChunkLengthPenaltySize = 30010
      MoptPipeliningSiteBl = 10011
      MoptPipeliningServerBl = 10012
      MoptMaxTotalConnections = 13
      MoptPushfunction = 20014
      MoptPushdata = 10015
      MoptLastentry = 10016
    end
    fun multi_assign = curl_multi_assign(multi_handle : M*, sockfd : SocketT, sockp : Void*) : Mcode
    alias Pushheaders = Void
    fun pushheader_bynum = curl_pushheader_bynum(h : Pushheaders*, num : LibC::SizeT) : LibC::Char*
    fun pushheader_byname = curl_pushheader_byname(h : Pushheaders*, name : LibC::Char*) : LibC::Char*
  end
end
